sudo: false
language: node_js
notifications:
  email: false
cache:
  - node_modules
node_js:
  - '6'
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm test
after_success:
  - npm run autorelease
branches:
  only:
    - "master"
