sudo: false
language: node_js
notifications:
  email: false
addons:
  apt:
    packages:
      - libgnome-keyring-dev
cache:
  - node_modules
node_js:
  - '6'
install:
  - npm install
before_script:
  - git config --global user.email "autorelease@travis-ci.org"
  - git config --global user.name "Autorelease CI"
  - npm run lint
script:
  - npm test
after_success:
  - npm run autorelease
branches:
  only:
    - "master"
